import os

sadrzaj = "*Pitanje nije završeno*\n\n[← Nazad na pitanja](index.md)\n"

opsta = [
    ("metode-u-patologiji", "Metode u patologiji"),
    ("predmet-proucavanja-patologije", "Predmet proučavanja patologije"),
    ("hipertrofija", "Hipertrofija"),
    ("hiperplazija", "Hiperplazija"),
    ("atrofija", "Atrofija"),
    ("metaplazija", "Metaplazija"),
    ("reparacija-tkiva", "Reparacija tkiva"),
    ("regeneracija", "Regeneracija"),
    ("zarastanje-rana", "Zarastanje rana"),
    ("organizacija", "Organizacija"),
    ("uzroci-ostecenja-celije", "Uzroci oštećenja ćelije"),
    ("mehanizam-celijskog-ostecenja", "Mehanizam ćelijskog oštećenja"),
    ("reverzibilne-ultrastrukturne-promene", "Reverzibilne ultrastrukturne promene oštećene ćelije"),
    ("ireverzibilne-ultrastrukturne-promene", "Ireverzibilne ultrastrukturne promene oštećene ćelije"),
    ("apoptoza", "Apoptoza"),
    ("nekroza", "Nekroza"),
    ("gangrena", "Gangrena"),
    ("patoloska-pigmentacija", "Patološka pigmentacija"),
    ("endogene-pigmentacije", "Endogene pigmentacije"),
    ("hemosideroza", "Hemosideroza"),
    ("zutica", "Žutica"),
    ("patoloska-kalcifikacija", "Patološka kalcifikacija"),
    ("stvaranje-kamenova", "Stvaranje kamenova (calculosis)"),
    ("nutritivne-bolesti", "Nutritivne bolesti"),
    ("hipovitaminoze", "Hipovitaminoze"),
    ("akumulacija-lipida", "Akumulacija lipida"),
    ("lipidoze", "Lipidoze"),
    ("glikogenoze", "Glikogenoze"),
    ("hijalina-promena", "Hijalina promena"),
    ("zapaljenja-definicija-etiologija-podela", "Zapaljenja (definicija, etiologija i podela)"),
    ("eksudativno-zapaljenje", "Eksudativno zapaljenje"),
    ("proliferativno-zapaljenje", "Proliferativno zapaljenje"),
    ("ishod-zapaljenja", "Ishod zapaljenja"),
    ("patologija-sepse", "Patologija sepse"),
    ("granulomatozna-zapaljenja", "Granulomatozna zapaljenja"),
    ("tuberkuloza", "Tuberkuloza"),
    ("sarkoidoza", "Sarkoidoza"),
    ("sifilis", "Sifilis"),
    ("aktinomikoza", "Aktinomikoza"),
    ("gljivicna-zapaljenja", "Gljivična zapaljenja"),
    ("parazitarna-zapaljenja", "Parazitarna zapaljenja"),
    ("edem", "Edem"),
    ("hiperemija-i-kongestija", "Hiperemija i kongestija"),
    ("krvarenje", "Krvarenje"),
    ("patologija-hemoragijske-dijateze", "Patologija hemoragijske dijateze"),
    ("tromboza", "Tromboza"),
    ("embolija", "Embolija"),
    ("ishemija", "Ishemija"),
    ("infarkt", "Infarkt"),
    ("patologija-soka", "Patologija šoka"),
    ("molekularne-osnove-genetskih-bolesti", "Molekularne osnove i biohemijski mehanizmi genetskih bolesti"),
    ("klasifikacija-genetskih-bolesti", "Klasifikacija genetskih bolesti"),
    ("patologija-imunskog-sistema", "Patologija imunskog sistema"),
    ("reakcije-preosetljivosti", "Reakcije preosetljivosti (hipersenzitivne reakcije)"),
    ("autoimunske-bolesti", "Patogeneza i morfologija sistemskih i organ-specifičnih autoimunskih bolesti"),
    ("imunodeficijencije", "Imunodeficijencije (primarne i sekundarne)"),
    ("patologija-transplantacije", "Patologija transplantacije"),
    ("amiloidoza", "Amiloidoza"),
    ("termicka-ostecenja", "Termička oštećenja"),
    ("radijaciona-ostecenja", "Radijaciona oštećenja"),
    ("poremecaji-razvoja", "Poremećaji razvoja"),
]

tumori = [
    ("tumori-terminologija-i-klasifikacija", "Tumori: terminologija i klasifikacija, građa i sekundarne promene"),
    ("karakteristike-benignih-i-malignih-tumora", "Opšte karakteristike benignih i malignih tumora"),
    ("karakteristike-epitelnih-i-mezenhimnih-tumora", "Opšte karakteristike epitelnih i mezenhimnih tumora"),
    ("tumorske-metastaze", "Tumorske metastaze"),
    ("lokalno-i-sistemsko-dejstvo-tumora", "Lokalno i sistemsko štetno dejstvo tumora"),
    ("karakteristike-i-kinetika-tumorskog-rasta", "Karakteristike i kinetika tumorskog rasta"),
    ("molekularna-osnova-kancerogeneze", "Molekularna osnova kancerogeneze"),
    ("gradiranje-i-stadijum-tumora", "Gradiranje i određivanje stadijuma tumora"),
    ("proteinski-produkti-proto-onkogena", "Proteinski produkti proto-onkogena i tumor-supresornih gena"),
    ("geni-regulatori-apoptoze", "Geni regulatori apoptoze, geni regulatori DNK popravke i tumori"),
    ("kariotipske-promene-u-tumorima", "Kariotipske promene u tumorima"),
    ("kancerogeneza", "Kancerogeneza (hemijska, zračna i virusna)"),
    ("imunitet-i-tumori", "Imunitet i tumori"),
    ("dijagnosticke-metode-u-onkoloskoj-patologiji", "Dijagnostičke metode u onkološkoj patologiji"),
    ("tumori-decjeg-doba", "Epidemiologija i etiologija tumora dečjeg doba; benigni tumori dečjeg doba"),
    ("neuroblasticni-tumori-i-wilms", "Neuroblastični tumori i Wilms-ov tumor"),
    ("tumori-srca", "Tumori srca i perikarda"),
    ("tumori-pluca", "Tumori pluća"),
    ("tumori-pleure", "Tumori pleure"),
    ("tumori-jednjaka", "Tumori jednjaka"),
    ("tumori-zeluca", "Tumori želuca"),
    ("karcinomi-zeluca", "Karcinomi želuca"),
    ("tumori-tankog-creva", "Tumori tankog creva"),
    ("tumori-debelog-creva", "Tumori i tumorima slične lezije debelog creva"),
    ("karcinomi-debelog-creva", "Karcinomi debelog creva i analnog kanala"),
    ("tumori-pankreasa", "Tumori pankreasa"),
    ("tumori-jetre", "Tumori jetre"),
    ("tumori-bilijarnog-trakta", "Tumori ekstrahepatičnog bilijarnog trakta"),
    ("benigni-tumori-stitaste-zlezde", "Benigni tumori štitaste žlezde"),
    ("maligni-tumori-stitaste-zlezde", "Maligni tumori štitaste žlezde"),
    ("tumori-endokrinog-pankreasa", "Tumori endokrinog pankreasa"),
    ("multipla-endokrina-neoplazija", "Multipla endokrina neoplazija tip I i II"),
    ("tumori-kore-nadbubrežne-zlezde", "Tumori kore nadbubrežne žlezde"),
    ("tumori-srzi-nadbubrežne-zlezde", "Tumori srži nadbubrežne žlezde"),
    ("ginekomastija-i-karcinom-muske-dojke", "Ginekomastija i karcinom muške dojke"),
    ("benigni-tumori-dojke", "Benigni tumori dojke"),
    ("maligni-tumori-dojke", "Maligni tumori dojke"),
    ("tumori-bubrega-odraslog-doba", "Tumori bubrega odraslog doba"),
    ("tumori-bubrega-decjeg-doba", "Tumori bubrega dečjeg doba"),
    ("tumori-donjih-mokracnih-puteva", "Tumori donjih mokraćnih puteva"),
    ("tumori-uterusa", "Tumori uterusa"),
    ("tumori-ovarijuma", "Tumori ovarijuma"),
    ("tumori-testisa", "Tumori testisa"),
    ("tumori-prostate", "Tumori prostate"),
    ("hodgkin-limfom", "Hodgkin-ov limfom"),
    ("non-hodgkin-limfomi", "Opšta patologija non-Hodgkin-ovih limfoma"),
    ("b-celijski-non-hodgkin-limfomi", "Klasifikacija B ćelijskih non-Hodgkin limfoma"),
    ("t-i-nk-celijski-limfomi", "Klasifikacija T i NK ćelijskih non-Hodgkin limfoma"),
    ("neoplazme-plazma-celija", "Neoplazme plazma ćelija"),
    ("patologija-leukemija", "Patologija akutnih i hroničnih leukemija"),
    ("mijelodisplasticni-sindrom", "Patologija mijelodisplastičnog sindroma i mijeloproliferativnih bolesti"),
    ("limfomi-koze", "Limfomi kože i kutane metastaze"),
    ("benigni-tumori-koze", "Benigni tumori i preinvazivne lezije kože"),
    ("planocelularni-i-bazocelularni-karcinom", "Planocelularni i bazocelularni karcinom kože"),
    ("benigni-melanotični-tumori", "Benigne melanotične promene (nevusi)"),
    ("maligni-melanotični-tumori", "Maligne melanotične promene (melanomi)"),
    ("mezenhimni-tumori-koze", "Mezenhimni tumori kože"),
    ("metastatski-tumori-kostiju", "Metastatski tumori kostiju"),
    ("klasifikacija-tumora-kostiju", "Klasifikacija tumora kostiju"),
    ("tumori-koji-stvaraju-kost", "Tumori koji stvaraju kost"),
    ("tumori-koji-stvaraju-hrskavicu", "Tumori koji stvaraju hrskavicu"),
    ("tumori-okruglih-celija-kosti", "Tumori okruglih ćelija kosti"),
    ("tumori-slicne-lezije-kostiju", "Tumori slične lezije kostiju"),
    ("tumori-zglobova", "Tumori i tumori slične lezije zglobova"),
    ("tumori-vezivnog-tkiva", "Tumori i tumorima slične lezije vezivnog tkiva"),
    ("fibrohistiocitni-tumori", "Fibrohistiocitni tumori"),
    ("tumori-masnog-tkiva", "Tumori masnog tkiva"),
    ("vaskularni-tumori", "Vaskularni tumori"),
    ("tumori-glatkog-misicnog-tkiva", "Tumori glatkog mišićnog tkiva"),
    ("tumori-poprecno-prugastog-misicnog-tkiva", "Tumori poprečno-prugastog mišićnog tkiva"),
    ("tumori-cns", "Tumori centralnog nervnog sistema"),
    ("neuroepitelijalni-tumori", "Neuroepitelijalni tumori (gliomi)"),
    ("tumori-mozdanica", "Tumori moždanica"),
    ("tumori-perifernih-nerva", "Tumori perifernih nerva i neurokutani sindromi"),
]

specijalna = [
    ("ateroskleroza", "Etiopatogeneza, morfologija i značaj ateroskleroze"),
    ("arterije-hipertenzija-dijabetes", "Promene na arterijama kod hipertenzije i dijabetesa"),
    ("vaskulitisi", "Vaskulitisi"),
    ("aneurizme", "Aneurizme"),
    ("patologija-vena-kapilara-limfnih-sudova", "Patologija vena, kapilara i limfnih sudova"),
    ("srcana-insuficijencija-pfo", "Srčana insuficijencija i patologija prolaznog ovalnog otvora"),
    ("urodjene-srcane-mane", "Urođene srčane mane"),
    ("ishemijska-bolest-srca", "Etiopatogeneza i klasifikacija ishemijske bolesti srca"),
    ("hipertenzivne-bolesti-srca", "Hipertenzivne bolesti srca"),
    ("reumatska-groznica", "Reumatska groznica"),
    ("stecene-srcane-mane", "Stečene srčane mane"),
    ("endokarditisi", "Infektivni i neinfektivni endokarditisi"),
    ("kardiomiopatije", "Kardiomiopatije"),
    ("perikarditisi", "Perikarditisi i strani sadržaj u perikardnoj kesi"),
    ("bronhitisi", "Bronhitisi"),
    ("hronicna-opstruktivna-bolest-pluca", "Hronična opstruktivna bolest pluća"),
    ("bronhijalna-astma", "Bronhijalna astma"),
    ("promene-lumena-bronha", "Promene lumena bronha"),
    ("cirkulatorni-poremecaji-pluca", "Cirkulatorni poremećaji u plućima"),
    ("atelektaza-pluca", "Atelektaza pluća"),
    ("emfizem-pluca", "Emfizem pluća"),
    ("respiratorni-distres-sindrom", "Respiratorni distres sindrom"),
    ("lobarna-pneumonija", "Lobarna pneumonija"),
    ("bronhopneumonija", "Bronhopneumonija"),
    ("apsces-i-gangrena-pluca", "Apsces i gangrena pluća"),
    ("intersticijalna-pneumonija", "Intersticijalna pneumonija"),
    ("tuberkuloza-pluca", "Tuberkuloza pluća"),
    ("fibroza-pluca", "Fibroza pluća"),
    ("patologija-pleure", "Patologija pleure"),
    ("tuberkulozna-kaverna", "Tuberkulozna kaverna"),
    ("gljivicna-i-parazitarna-zapaljenja-pluca", "Gljivična i parazitarna zapaljenja pluća"),
    ("restriktivni-sindrom-pluca", "Restriktivni sindrom pluća"),
    ("pneumokonioze", "Pneumokonioze"),
    ("patologija-usne-supljine", "Patologija usne šupljine"),
    ("patologija-zdrela-vrata-medijastinuma", "Patologija ždrela, vrata i medijastinuma"),
    ("netumorska-patologija-jednjaka", "Netumorska patologija jednjaka"),
    ("urodjene-anomalije-git", "Urođene anomalije gastrointestinalnog trakta"),
    ("gastritis", "Gastritis"),
    ("pepticki-ulkus", "Peptički ulkus"),
    ("intestinalna-opstrukcija", "Intestinalna opstrukcija"),
    ("inflamatorne-bolesti-tankog-creva", "Inflamatorne bolesti tankog creva"),
    ("mehanicki-i-neuromuskularni-poremecaji-git", "Mehanički i neuromuskularni poremećaji gastrointestinalnog trakta"),
    ("kolitis", "Kolitis"),
    ("patologija-apendiksa", "Patologija apendiksa"),
    ("patologija-pankreatitisa", "Patologija pankreatitisa"),
    ("patologija-peritoneuma", "Patologija peritoneuma"),
    ("opsta-patologija-ostecenja-jetre", "Opšta patologija oštećenja jetre"),
    ("kongenitalne-anomalije-jetre", "Kongenitalne anomalije i bolesti jetre kod dece"),
    ("dismetabolicke-hepatopatije", "Dismetaboličke hepatopatije"),
    ("cirkulacijski-poremecaji-jetre", "Cirkulacijski poremećaji i vaskularne bolesti jetre"),
    ("akutni-virusni-hepatitis", "Akutni virusni hepatitis"),
    ("apscesi-jetre", "Apscesi jetre"),
    ("ostecenje-jetre-lekovima", "Oštećenje jetre lekovima i toksinima"),
    ("alkoholna-bolest-jetre", "Alkoholna bolest jetre"),
    ("hronicni-hepatitis", "Hronični hepatitis"),
    ("holestaza", "Holestaza"),
    ("ciroza-jetre", "Ciroza jetre"),
    ("holelitijaza", "Holelitijaza"),
    ("holecistitis", "Holecistitis"),
    ("stecene-bolesti-bilijarnih-duktusa", "Stečene bolesti bilijarnih duktusa"),
    ("transplantacijska-patologija-hepatobilijarnog-trakta", "Transplantacijska patologija hepatobilijarnog trakta"),
    ("hipotireoidizam", "Hipotireoidizam"),
    ("tireotoksikoza", "Tireotoksikoza"),
    ("strume-stitaste-zlezde", "Strume štitaste žlezde"),
    ("tireoiditisi", "Tireoiditisi"),
    ("patologija-timusa", "Patologija timusa"),
    ("patologija-myasthenia-gravis", "Patologija myasthenia gravis"),
    ("primarni-hiperparatireoidizam", "Patologija primarnog hiperparatireoidizma"),
    ("sekundarni-hiperparatireoidizam", "Patologija sekundarnog hiperparatireoidizma"),
    ("patologija-diabetes-mellitus", "Patologija diabetes mellitus-a"),
    ("vaskularne-lezije-nadbubrežne-zlezde", "Vaskularne lezije i zapaljenja nadbubrežne žlezde"),
    ("zapaljenje-dojke", "Zapaljenje dojke i nekroza masnog tkiva dojke"),
    ("fibrocisticna-promena-dojke", "Fibrocistična promena dojke"),
    ("urodjene-anomalije-urinarnog-sistema", "Urođene anomalije urinarnog sistema"),
    ("etiopatogeneza-primarnih-bolesti-glomerula", "Etiopatogeneza primarnih bolesti glomerula"),
    ("glomerulonefritisi-nefrotski-sindrom", "Primarni glomerulonefritisi koji se klinički ispoljavaju nefrotskim sindromom"),
    ("glomerulonefritisi-nefriticki-sindrom", "Primarni glomerulonefritisi koji se klinički ispoljavaju nefritičkim sindromom"),
    ("glomerulonefritis-sa-polumesecima", "Glomerulonefritis sa stvaranjem polumeseca. Rapidnoprogresivni glomerulonefritis. Goodpasture sindrom"),
    ("bubrezni-sistemske-bolesti", "Morfološke promene u bubrezima u sistemskim bolestima"),
    ("bubrezni-metabolicke-bolesti", "Morfološke promene u bubrezima u metaboličkim bolestima"),
    ("vaskularne-bolesti-bubrega", "Vaskularne bolesti bubrega"),
    ("bubrezi-sistemski-vaskulitisi", "Promene u bubrezima kod sistemskih vaskulitisa"),
    ("pijelonefritis", "Akutni i hronični pijelonefritis"),
    ("tuberkuloza-bubrega", "Tuberkuloza bubrega"),
    ("tubulointersticijske-nefropatije", "Tubulointersticijske nefropatije. Balkanska endemska nefropatija"),
    ("nefrolitijaza", "Nefrolitijaza"),
    ("opstruktivne-uropatije", "Opstruktivne uropatije: vezikoureteralni refluks, hidronefroza i hidroureter"),
    ("akutna-i-hronicna-bubrezna-insuficijencija", "Morfološki supstrat akutne i hronične bubrežne insuficijencije"),
    ("transplantiran-bubreg", "Morfološke promene u transplantiranom bubregu"),
    ("zapaljenja-donjih-mokracnih-puteva", "Zapaljenja donjih mokraćnih puteva"),
    ("patologija-vulve", "Patologija vulve"),
    ("patologija-vagine", "Patologija vagine"),
    ("patologija-cerviksa", "Patologija cerviksa"),
    ("netumorska-patologija-uterusa", "Netumorska patologija uterusa"),
    ("patologija-jajovoda", "Patologija jajovoda"),
    ("netumorska-patologija-ovarijuma", "Netumorska patologija ovarijuma"),
    ("poremecaji-trudnoce", "Poremećaji rane trudnoće i poremećaji kasne trudnoće"),
    ("abnormalnosti-placente", "Abnormalnosti placente i blizanačke placente, inflamacije i infekcije placente, toksemija trudnoće"),
    ("gestacione-trofoblastne-bolesti", "Gestacione trofoblastne bolesti"),
    ("patologija-penisa-i-skrotuma", "Patologija penisa i skrotuma"),
    ("netumorska-patologija-testisa", "Netumorska patologija testisa i tunike vaginalis"),
    ("netumorska-patologija-prostate", "Netumorska patologija prostate"),
    ("bolesti-limfnih-cvorova", "Neneoplastične bolesti limfnih čvorova"),
    ("patologija-slezine", "Patologija bolesti slezine"),
    ("patologija-anemija", "Patologija anemija"),
    ("dermatoze", "Spongiformne, dodirne, psorijatiformne i vezikulo-bulozne dermatoze"),
    ("infektivne-i-granulomatozne-dermatoze", "Infektivne i granulomatozne dermatoze; panikulitisi"),
    ("patologija-ocnih-kapaka", "Patologija očnih kapaka, suznog aparata i vežnjače"),
    ("patologija-sociva-stakastog-tela-retine", "Patologija sočiva, staklastog tela i retine"),
    ("patologija-uha", "Patologija uha"),
    ("degenerativna-oboljenja-zglobova", "Degenerativna oboljenja zglobova"),
    ("inflamatorna-oboljenja-zglobova", "Inflamatorna oboljenja zglobova"),
    ("osteoporoza", "Osteoporoza"),
    ("anomalije-razvoja-skeleta", "Anomalije razvoja skeleta"),
    ("metabolicke-bolesti-kostiju", "Metaboličke bolesti kostiju"),
    ("pedzetova-bolest", "Pedžetova bolest"),
    ("sistemske-bolesti-skeletne-manifestacije", "Sistemske bolesti sa skeletnim manifestacijama"),
    ("infektivna-zapaljenja-kostiju", "Infektivna zapaljenja kostiju"),
    ("regeneracija-kostano-tkivo", "Regeneracija koštanog tkiva"),
    ("metabolicka-oboljenja-zglobova", "Metabolička oboljenja zglobova"),
    ("infektivna-oboljenja-zglobova", "Infektivna oboljenja zglobova"),
    ("bolesti-sinovina-tetiva-burzi", "Bolesti sinovija, tetiva i burzi"),
    ("patologija-celija-tkiva-cns", "Patologija ćelija i tkiva centralnog nervnog sistema"),
    ("povisen-intrakranijalni-pritisak", "Patologija povišenog intrakranijalnog pritiska, edem mozga i hidrocefalus"),
    ("urodjene-malformacije-cns", "Urođene malformacije centralnog nervnog sistema"),
    ("trauma-cns", "Trauma centralnog nervnog sistema i perinatalno oštećenje mozga"),
    ("cerebrovaskularne-bolesti", "Cerebrovaskularne bolesti, infarkt mozga i selektivna vulnerabilnost neurona"),
    ("hipertenzivno-mozdano-krvarenje", "Hipertenzivno moždano krvarenje"),
    ("aneurizme-krvnih-sudova-mozga", "Aneurizme krvnih sudova osnovice mozga"),
    ("gnojna-zapaljenja-mozdanica", "Gnojna zapaljenja moždanica i mozga"),
    ("tuberkulozno-zapaljenje-cns", "Tuberkulozno zapaljenje centralnog nervnog sistema, neurosifilis i neuroborelioza"),
    ("virusni-meningoencefalitisi", "Virusni meningoencefalitisi i neuropatologija AIDS-a"),
    ("oboljenja-sporih-virusa", "Oboljenja mozga izazvana sporim virusima"),
    ("gljivicne-parazitarne-rikecijske-infekcije-cns", "Gljivične, parazitarne i rikecijske infekcije centralnog nervnog sistema"),
    ("patologija-prionskih-bolesti", "Patologija prionskih bolesti"),
    ("patologija-demijelinizirajucih-bolesti", "Patologija demijelinizirajućih bolesti"),
    ("patologija-degenerativnih-bolesti-kore", "Patologija degenerativnih bolesti velikomoždane kore"),
    ("patologija-degenerativnih-bolesti-bazalnih-ganglija", "Patologija degenerativnih bolesti bazalnih ganglija, moždanog stabla i spinocerebelarne degeneracije"),
    ("patologija-degenerativnih-bolesti-motornog-neurona", "Patologija degenerativnih bolesti motornog neurona"),
    ("neuronalne-bolesti-nakupljanja", "Patologija neuronalnih bolesti nakupljanja i leukodistrofija"),
    ("toksicne-metabolicke-encefalopatije", "Patologija toksičnih, stečenih metaboličkih i deficitom vitamina izazvanih encefalopatija"),
    ("patologija-hipofize-i-hipotalamusa", "Patologija hipofize i hipotalamusa"),
    ("bazicni-patoloski-procesi-perifernog-nerva", "Bazični patološki procesi perifernog nerva"),
    ("inflamatorne-metabolicke-neuropatije", "Inflamatorne, metaboličke, toksičke i hereditarne neuropatije"),
    ("opsta-patologija-misica", "Opšta patologija mišića"),
    ("patologija-neurogenih-misicnih-bolesti", "Patologija neurogenih mišićnih bolesti - neuropatije"),
    ("patologija-primarnih-misicnih-bolesti", "Patologija primarnih mišićnih bolesti – miopatije"),
]

sekcije = {
    r"docs\treca-godina\patologija\opsta-patologija": opsta,
    r"docs\treca-godina\patologija\patologija-tumora": tumori,
    r"docs\treca-godina\patologija\specijalna-patologija": specijalna,
}

for folder, pitanja in sekcije.items():
    for ime, naslov in pitanja:
        putanja = os.path.join(folder, f"{ime}.md")
        with open(putanja, "w", encoding="utf-8") as f:
            f.write(f"# {naslov}\n\n*Pitanje nije završeno*\n\n[← Nazad na pitanja](index.md)\n")
        print(f"Kreiran: {putanja}")

print("Gotovo!")

