import os

opsta = [
    ("metode-u-patologiji", "Metode u patologiji"),
    ("predmet-proucavanja-patologije", "Predmet proučavanja patologije"),
    ("hipertrofija", "Hipertrofija"),
    ("hiperplazija", "Hiperplazija"),
    ("atrofija", "Atrofija"),
    ("metaplazija", "Metaplazija"),
    ("reparacija-tkiva", "Reparacija tkiva"),
    ("regeneracija", "Regeneracija"),
    ("zarastanje-rana", "Zarastanje rana"),
    ("organizacija", "Organizacija"),
    ("uzroci-ostecenja-celije", "Uzroci ostecenja celije"),
    ("mehanizam-celijskog-ostecenja", "Mehanizam celijskog ostecenja"),
    ("reverzibilne-ultrastrukturne-promene", "Reverzibilne ultrastrukturne promene ostecene celije"),
    ("ireverzibilne-ultrastrukturne-promene", "Ireverzibilne ultrastrukturne promene ostecene celije"),
    ("apoptoza", "Apoptoza"),
    ("nekroza", "Nekroza"),
    ("gangrena", "Gangrena"),
    ("patoloska-pigmentacija", "Patoloska pigmentacija"),
    ("endogene-pigmentacije", "Endogene pigmentacije"),
    ("hemosideroza", "Hemosideroza"),
    ("zutica", "Zutica"),
    ("patoloska-kalcifikacija", "Patoloska kalcifikacija"),
    ("stvaranje-kamenova", "Stvaranje kamenova (calculosis)"),
    ("nutritivne-bolesti", "Nutritivne bolesti"),
    ("hipovitaminoze", "Hipovitaminoze"),
    ("akumulacija-lipida", "Akumulacija lipida"),
    ("lipidoze", "Lipidoze"),
    ("glikogenoze", "Glikogenoze"),
    ("hijalina-promena", "Hijalina promena"),
    ("zapaljenja-definicija-etiologija-podela", "Zapaljenja (definicija, etiologija i podela)"),
    ("eksudativno-zapaljenje", "Eksudativno zapaljenje"),
    ("proliferativno-zapaljenje", "Proliferativno zapaljenje"),
    ("ishod-zapaljenja", "Ishod zapaljenja"),
    ("patologija-sepse", "Patologija sepse"),
    ("granulomatozna-zapaljenja", "Granulomatozna zapaljenja"),
    ("tuberkuloza", "Tuberkuloza"),
    ("sarkoidoza", "Sarkoidoza"),
    ("sifilis", "Sifilis"),
    ("aktinomikoza", "Aktinomikoza"),
    ("gljivicna-zapaljenja", "Gljivicna zapaljenja"),
    ("parazitarna-zapaljenja", "Parazitarna zapaljenja"),
    ("edem", "Edem"),
    ("hiperemija-i-kongestija", "Hiperemija i kongestija"),
    ("krvarenje", "Krvarenje"),
    ("patologija-hemoragijske-dijateze", "Patologija hemoragijske dijateze"),
    ("tromboza", "Tromboza"),
    ("embolija", "Embolija"),
    ("ishemija", "Ishemija"),
    ("infarkt", "Infarkt"),
    ("patologija-soka", "Patologija soka"),
    ("molekularne-osnove-genetskih-bolesti", "Molekularne osnove i biohemijski mehanizmi genetskih bolesti"),
    ("klasifikacija-genetskih-bolesti", "Klasifikacija genetskih bolesti"),
    ("patologija-imunskog-sistema", "Patologija imunskog sistema"),
    ("reakcije-preosetljivosti", "Reakcije preosetljivosti (hipersenzitivne reakcije)"),
    ("autoimunske-bolesti", "Patogeneza i morfologija autoimunskih bolesti"),
    ("imunodeficijencije", "Imunodeficijencije (primarne i sekundarne)"),
    ("patologija-transplantacije", "Patologija transplantacije"),
    ("amiloidoza", "Amiloidoza"),
    ("termicka-ostecenja", "Termicka ostecenja"),
    ("radijaciona-ostecenja", "Radijaciona ostecenja"),
    ("poremecaji-razvoja", "Poremecaji razvoja"),
]

tumori = [
    ("tumori-terminologija-i-klasifikacija", "Tumori: terminologija i klasifikacija"),
    ("karakteristike-benignih-i-malignih-tumora", "Opste karakteristike benignih i malignih tumora"),
    ("karakteristike-epitelnih-i-mezenhimnih-tumora", "Opste karakteristike epitelnih i mezenhimnih tumora"),
    ("tumorske-metastaze", "Tumorske metastaze"),
    ("lokalno-i-sistemsko-dejstvo-tumora", "Lokalno i sistemsko stetno dejstvo tumora"),
    ("karakteristike-i-kinetika-tumorskog-rasta", "Karakteristike i kinetika tumorskog rasta"),
    ("molekularna-osnova-kancerogeneze", "Molekularna osnova kancerogeneze"),
    ("gradiranje-i-stadijum-tumora", "Gradiranje i odredjivanje stadijuma tumora"),
    ("proteinski-produkti-proto-onkogena", "Proteinski produkti proto-onkogena i tumor-supresornih gena"),
    ("geni-regulatori-apoptoze", "Geni regulatori apoptoze i DNK popravke"),
    ("kariotipske-promene-u-tumorima", "Kariotipske promene u tumorima"),
    ("kancerogeneza", "Kancerogeneza (hemijska, zracna i virusna)"),
    ("imunitet-i-tumori", "Imunitet i tumori"),
    ("dijagnosticke-metode-u-onkoloskoj-patologiji", "Dijagnosticke metode u onoloskoj patologiji"),
    ("tumori-decjeg-doba", "Epidemiologija i etiologija tumora decjeg doba"),
    ("neuroblasticni-tumori-i-wilms", "Neuroblasticni tumori i Wilms-ov tumor"),
    ("tumori-srca", "Tumori srca i perikarda"),
    ("tumori-pluca", "Tumori pluca"),
    ("tumori-pleure", "Tumori pleure"),
    ("tumori-jednjaka", "Tumori jednjaka"),
    ("tumori-zeluca", "Tumori zeluca"),
    ("karcinomi-zeluca", "Karcinomi zeluca"),
    ("tumori-tankog-creva", "Tumori tankog creva"),
    ("tumori-debelog-creva", "Tumori debelog creva"),
    ("karcinomi-debelog-creva", "Karcinomi debelog creva i analnog kanala"),
    ("tumori-pankreasa", "Tumori pankreasa"),
    ("tumori-jetre", "Tumori jetre"),
    ("tumori-bilijarnog-trakta", "Tumori ekstrahepaticnog bilijarnog trakta"),
    ("benigni-tumori-stitaste-zlezde", "Benigni tumori stitaste zlezde"),
    ("maligni-tumori-stitaste-zlezde", "Maligni tumori stitaste zlezde"),
    ("tumori-endokrinog-pankreasa", "Tumori endokrinog pankreasa"),
    ("multipla-endokrina-neoplazija", "Multipla endokrina neoplazija tip I i II"),
    ("tumori-kore-nadbubrežne-zlezde", "Tumori kore nadbubrežne zlezde"),
    ("tumori-srzi-nadbubrežne-zlezde", "Tumori srzi nadbubrežne zlezde"),
    ("ginekomastija-i-karcinom-muske-dojke", "Ginekomastija i karcinom muske dojke"),
    ("benigni-tumori-dojke", "Benigni tumori dojke"),
    ("maligni-tumori-dojke", "Maligni tumori dojke"),
    ("tumori-bubrega-odraslog-doba", "Tumori bubrega odraslog doba"),
    ("tumori-bubrega-decjeg-doba", "Tumori bubrega decjeg doba"),
    ("tumori-donjih-mokracnih-puteva", "Tumori donjih mokracnih puteva"),
    ("tumori-uterusa", "Tumori uterusa"),
    ("tumori-ovarijuma", "Tumori ovarijuma"),
    ("tumori-testisa", "Tumori testisa"),
    ("tumori-prostate", "Tumori prostate"),
    ("hodgkin-limfom", "Hodgkin-ov limfom"),
    ("non-hodgkin-limfomi", "Opsta patologija non-Hodgkin-ovih limfoma"),
    ("b-celijski-non-hodgkin-limfomi", "Klasifikacija B celijskih non-Hodgkin limfoma"),
    ("t-i-nk-celijski-limfomi", "Klasifikacija T i NK celijskih non-Hodgkin limfoma"),
    ("neoplazme-plazma-celija", "Neoplazme plazma celija"),
    ("patologija-leukemija", "Patologija akutnih i hronicnih leukemija"),
    ("mijelodisplasticni-sindrom", "Patologija mijelodisplasticnog sindroma i mijeloproliferativnih bolesti"),
    ("limfomi-koze", "Limfomi koze i kutane metastaze"),
    ("benigni-tumori-koze", "Benigni tumori i preinvazivne lezije koze"),
    ("planocelularni-i-bazocelularni-karcinom", "Planocelularni i bazocelularni karcinom koze"),
    ("benigni-melanotični-tumori", "Benigne melanotične promene (nevusi)"),
    ("maligni-melanotični-tumori", "Maligne melanotične promene (melanomi)"),
    ("mezenhimni-tumori-koze", "Mezenhimni tumori koze"),
    ("metastatski-tumori-kostiju", "Metastatski tumori kostiju"),
    ("klasifikacija-tumora-kostiju", "Klasifikacija tumora kostiju"),
    ("tumori-koji-stvaraju-kost", "Tumori koji stvaraju kost"),
    ("tumori-koji-stvaraju-hrskavicu", "Tumori koji stvaraju hrskavicu"),
    ("tumori-okruglih-celija-kosti", "Tumori okruglih celija kosti"),
    ("tumori-slicne-lezije-kostiju", "Tumori slicne lezije kostiju"),
    ("tumori-zglobova", "Tumori i slicne lezije zglobova"),
    ("tumori-vezivnog-tkiva", "Tumori i slicne lezije vezivnog tkiva"),
    ("fibrohistiocitni-tumori", "Fibrohistiocitni tumori"),
    ("tumori-masnog-tkiva", "Tumori masnog tkiva"),
    ("vaskularni-tumori", "Vaskularni tumori"),
    ("tumori-glatkog-misicnog-tkiva", "Tumori glatkog misicnog tkiva"),
    ("tumori-poprecno-prugastog-misicnog-tkiva", "Tumori poprecno-prugastog misicnog tkiva"),
    ("tumori-cns", "Tumori centralnog nervnog sistema"),
    ("neuroepitelijalni-tumori", "Neuroepitelijalni tumori (gliomi)"),
    ("tumori-mozdanica", "Tumori mozdanica"),
    ("tumori-perifernih-nerva", "Tumori perifernih nerva i neurokutani sindromi"),
]

specijalna = [
    ("ateroskleroza", "Etiopatogeneza, morfologija i znacaj ateroskleroze"),
    ("arterije-hipertenzija-dijabetes", "Promene na arterijama kod hipertenzije i dijabetesa"),
    ("vaskulitisi", "Vaskulitisi"),
    ("aneurizme", "Aneurizme"),
    ("patologija-vena-kapilara-limfnih-sudova", "Patologija vena, kapilara i limfnih sudova"),
    ("srcana-insuficijencija-pfo", "Srcana insuficijencija i patologija prolaznog ovalnog otvora"),
    ("urodjene-srcane-mane", "Urodjene srcane mane"),
    ("ishemijska-bolest-srca", "Etiopatogeneza i klasifikacija ishemijske bolesti srca"),
    ("hipertenzivne-bolesti-srca", "Hipertenzivne bolesti srca"),
    ("reumatska-groznica", "Reumatska groznica"),
    ("stecene-srcane-mane", "Stecene srcane mane"),
    ("endokarditisi", "Infektivni i neinfektivni endokarditisi"),
    ("kardiomiopatije", "Kardiomiopatije"),
    ("perikarditisi", "Perikarditisi i strani sadrzaj u perikardnoj kesi"),
    ("bronhitisi", "Bronhitisi"),
    ("hronicna-opstruktivna-bolest-pluca", "Hronicna opstruktivna bolest pluca"),
    ("bronhijalna-astma", "Bronhijalna astma"),
    ("promene-lumena-bronha", "Promene lumena bronha"),
    ("cirkulatorni-poremecaji-pluca", "Cirkulatorni poremecaji u plucima"),
    ("atelektaza-pluca", "Atelektaza pluca"),
    ("emfizem-pluca", "Emfizem pluca"),
    ("respiratorni-distres-sindrom", "Respiratorni distres sindrom"),
    ("lobarna-pneumonija", "Lobarna pneumonija"),
    ("bronhopneumonija", "Bronhopneumonija"),
    ("apsces-i-gangrena-pluca", "Apsces i gangrena pluca"),
    ("intersticijalna-pneumonija", "Intersticijalna pneumonija"),
    ("tuberkuloza-pluca", "Tuberkuloza pluca"),
    ("fibroza-pluca", "Fibroza pluca"),
    ("patologija-pleure", "Patologija pleure"),
    ("tuberkulozna-kaverna", "Tuberkulozna kaverna"),
    ("gljivicna-i-parazitarna-zapaljenja-pluca", "Gljivicna i parazitarna zapaljenja pluca"),
    ("restriktivni-sindrom-pluca", "Restriktivni sindrom pluca"),
    ("pneumokonioze", "Pneumokonioze"),
    ("patologija-usne-supljine", "Patologija usne supljine"),
    ("patologija-zdrela-vrata-medijastinuma", "Patologija zdrela, vrata i medijastinuma"),
    ("netumorska-patologija-jednjaka", "Netumorska patologija jednjaka"),
    ("urodjene-anomalije-git", "Urodjene anomalije gastrointestinalnog trakta"),
    ("gastritis", "Gastritis"),
    ("pepticki-ulkus", "Pepticki ulkus"),
    ("intestinalna-opstrukcija", "Intestinalna opstrukcija"),
    ("inflamatorne-bolesti-tankog-creva", "Inflamatorne bolesti tankog creva"),
    ("mehanicki-i-neuromuskularni-poremecaji-git", "Mehanicki i neuromuskularni poremecaji gastrointestinalnog trakta"),
    ("kolitis", "Kolitis"),
    ("patologija-apendiksa", "Patologija apendiksa"),
    ("patologija-pankreatitisa", "Patologija pankreatitisa"),
    ("patologija-peritoneuma", "Patologija peritoneuma"),
    ("opsta-patologija-ostecenja-jetre", "Opsta patologija ostecenja jetre"),
    ("kongenitalne-anomalije-jetre", "Kongenitalne anomalije i bolesti jetre kod dece"),
    ("dismetabolicke-hepatopatije", "Dismetabolicke hepatopatije"),
    ("cirkulacijski-poremecaji-jetre", "Cirkulacijski poremecaji i vaskularne bolesti jetre"),
    ("akutni-virusni-hepatitis", "Akutni virusni hepatitis"),
    ("apscesi-jetre", "Apscesi jetre"),
    ("ostecenje-jetre-lekovima", "Ostecenje jetre lekovima i toksinima"),
    ("alkoholna-bolest-jetre", "Alkoholna bolest jetre"),
    ("hronicni-hepatitis", "Hronicni hepatitis"),
    ("holestaza", "Holestaza"),
    ("ciroza-jetre", "Ciroza jetre"),
    ("holelitijaza", "Holelitijaza"),
    ("holecistitis", "Holecistitis"),
    ("stecene-bolesti-bilijarnih-duktusa", "Stecene bolesti bilijarnih duktusa"),
    ("transplantacijska-patologija-hepatobilijarnog-trakta", "Transplantacijska patologija hepatobilijarnog trakta"),
    ("hipotireoidizam", "Hipotireoidizam"),
    ("tireotoksikoza", "Tireotoksikoza"),
    ("strume-stitaste-zlezde", "Strume stitaste zlezde"),
    ("tireoiditisi", "Tireoiditisi"),
    ("patologija-timusa", "Patologija timusa"),
    ("patologija-myasthenia-gravis", "Patologija myasthenia gravis"),
    ("primarni-hiperparatireoidizam", "Patologija primarnog hiperparatireoidizma"),
    ("sekundarni-hiperparatireoidizam", "Patologija sekundarnog hiperparatireoidizma"),
    ("patologija-diabetes-mellitus", "Patologija diabetes mellitus-a"),
    ("vaskularne-lezije-nadbubrežne-zlezde", "Vaskularne lezije i zapaljenja nadbubrežne zlezde"),
    ("zapaljenje-dojke", "Zapaljenje dojke i nekroza masnog tkiva dojke"),
    ("fibrocisticna-promena-dojke", "Fibrocisticna promena dojke"),
    ("urodjene-anomalije-urinarnog-sistema", "Urodjene anomalije urinarnog sistema"),
    ("etiopatogeneza-primarnih-bolesti-glomerula", "Etiopatogeneza primarnih bolesti glomerula"),
    ("glomerulonefritisi-nefrotski-sindrom", "Primarni glomerulonefritisi sa nefrotskim sindromom"),
    ("glomerulonefritisi-nefriticki-sindrom", "Primarni glomerulonefritisi sa nefritickim sindromom"),
    ("glomerulonefritis-sa-polumesecima", "Glomerulonefritis sa stvaranjem polumeseca"),
    ("bubrezni-sistemske-bolesti", "Morfoloske promene u bubrezima u sistemskim bolestima"),
    ("bubrezni-metabolicke-bolesti", "Morfoloske promene u bubrezima u metabolickim bolestima"),
    ("vaskularne-bolesti-bubrega", "Vaskularne bolesti bubrega"),
    ("bubrezi-sistemski-vaskulitisi", "Promene u bubrezima kod sistemskih vaskulitisa"),
    ("pijelonefritis", "Akutni i hronicni pijelonefritis"),
    ("tuberkuloza-bubrega", "Tuberkuloza bubrega"),
    ("tubulointersticijske-nefropatije", "Tubulointersticijske nefropatije"),
    ("nefrolitijaza", "Nefrolitijaza"),
    ("opstruktivne-uropatije", "Opstruktivne uropatije"),
    ("akutna-i-hronicna-bubrezna-insuficijencija", "Morfoloski supstrat akutne i hronicne bubrezne insuficijencije"),
    ("transplantiran-bubreg", "Morfoloske promene u transplantiranom bubregu"),
    ("zapaljenja-donjih-mokracnih-puteva", "Zapaljenja donjih mokracnih puteva"),
    ("patologija-vulve", "Patologija vulve"),
    ("patologija-vagine", "Patologija vagine"),
    ("patologija-cerviksa", "Patologija cerviksa"),
    ("netumorska-patologija-uterusa", "Netumorska patologija uterusa"),
    ("patologija-jajovoda", "Patologija jajovoda"),
    ("netumorska-patologija-ovarijuma", "Netumorska patologija ovarijuma"),
    ("poremecaji-trudnoce", "Poremecaji rane i kasne trudnoce"),
    ("abnormalnosti-placente", "Abnormalnosti placente"),
    ("gestacione-trofoblastne-bolesti", "Gestacione trofoblastne bolesti"),
    ("patologija-penisa-i-skrotuma", "Patologija penisa i skrotuma"),
    ("netumorska-patologija-testisa", "Netumorska patologija testisa i tunike vaginalis"),
    ("netumorska-patologija-prostate", "Netumorska patologija prostate"),
    ("bolesti-limfnih-cvorova", "Neneoplasticne bolesti limfnih cvorova"),
    ("patologija-slezine", "Patologija bolesti slezine"),
    ("patologija-anemija", "Patologija anemija"),
    ("dermatoze", "Spongiformne, dodirne, psorijatiformne i vezikulo-bulozne dermatoze"),
    ("infektivne-i-granulomatozne-dermatoze", "Infektivne i granulomatozne dermatoze; panikulitisi"),
    ("patologija-ocnih-kapaka", "Patologija ocnih kapaka, suznog aparata i veznjace"),
    ("patologija-sociva-stakastog-tela-retine", "Patologija sociva, staklastog tela i retine"),
    ("patologija-uha", "Patologija uha"),
    ("degenerativna-oboljenja-zglobova", "Degenerativna oboljenja zglobova"),
    ("inflamatorna-oboljenja-zglobova", "Inflamatorna oboljenja zglobova"),
    ("osteoporoza", "Osteoporoza"),
    ("anomalije-razvoja-skeleta", "Anomalije razvoja skeleta"),
    ("metabolicke-bolesti-kostiju", "Metabolicke bolesti kostiju"),
    ("pedzetova-bolest", "Pedzetova bolest"),
    ("sistemske-bolesti-skeletne-manifestacije", "Sistemske bolesti sa skeletnim manifestacijama"),
    ("infektivna-zapaljenja-kostiju", "Infektivna zapaljenja kostiju"),
    ("regeneracija-kostano-tkivo", "Regeneracija kostnog tkiva"),
    ("metabolicka-oboljenja-zglobova", "Metabolicka oboljenja zglobova"),
    ("infektivna-oboljenja-zglobova", "Infektivna oboljenja zglobova"),
    ("bolesti-sinovina-tetiva-burzi", "Bolesti sinovija, tetiva i burzi"),
    ("patologija-celija-tkiva-cns", "Patologija celija i tkiva centralnog nervnog sistema"),
    ("povisen-intrakranijalni-pritisak", "Povisen intrakranijalni pritisak, edem mozga i hidrocefalus"),
    ("urodjene-malformacije-cns", "Urodjene malformacije centralnog nervnog sistema"),
    ("trauma-cns", "Trauma centralnog nervnog sistema i perinatalno ostecenje mozga"),
    ("cerebrovaskularne-bolesti", "Cerebrovaskularne bolesti i infarkt mozga"),
    ("hipertenzivno-mozdano-krvarenje", "Hipertenzivno mozdano krvarenje"),
    ("aneurizme-krvnih-sudova-mozga", "Aneurizme krvnih sudova osnovice mozga"),
    ("gnojna-zapaljenja-mozdanica", "Gnojna zapaljenja mozdanica i mozga"),
    ("tuberkulozno-zapaljenje-cns", "Tuberkulozno zapaljenje CNS, neurosifilis i neuroborelioza"),
    ("virusni-meningoencefalitisi", "Virusni meningoencefalitisi i neuropatologija AIDS-a"),
    ("oboljenja-sporih-virusa", "Oboljenja mozga izazvana sporim virusima"),
    ("gljivicne-parazitarne-rikecijske-infekcije-cns", "Gljivicne, parazitarne i rikecijske infekcije CNS"),
    ("patologija-prionskih-bolesti", "Patologija prionskih bolesti"),
    ("patologija-demijelinizirajucih-bolesti", "Patologija demijelinizirajucih bolesti"),
    ("patologija-degenerativnih-bolesti-kore", "Patologija degenerativnih bolesti velikomozdane kore"),
    ("patologija-degenerativnih-bolesti-bazalnih-ganglija", "Patologija degenerativnih bolesti bazalnih ganglija"),
    ("patologija-degenerativnih-bolesti-motornog-neurona", "Patologija degenerativnih bolesti motornog neurona"),
    ("neuronalne-bolesti-nakupljanja", "Patologija neuronalnih bolesti nakupljanja i leukodistrofija"),
    ("toksicne-metabolicke-encefalopatije", "Patologija toksicnih i metabolickih encefalopatija"),
    ("patologija-hipofize-i-hipotalamusa", "Patologija hipofize i hipotalamusa"),
    ("bazicni-patoloski-procesi-perifernog-nerva", "Bazicni patoloski procesi perifernog nerva"),
    ("inflamatorne-metabolicke-neuropatije", "Inflamatorne, metabolicke, toksicke i hereditarne neuropatije"),
    ("opsta-patologija-misica", "Opsta patologija misica"),
    ("patologija-neurogenih-misicnih-bolesti", "Patologija neurogenih misicnih bolesti"),
    ("patologija-primarnih-misicnih-bolesti", "Patologija primarnih misicnih bolesti - miopatije"),
]

def kreiraj_index(folder, naslov, pitanja):
    putanja = os.path.join(folder, "index.md")
    with open(putanja, "w", encoding="utf-8") as f:
        f.write(f"# {naslov}\n\n")
        for i, (ime, naziv) in enumerate(pitanja, 1):
            f.write(f"{i}. [{naziv}]({ime}.md)\n")
    print(f"Kreiran index: {putanja}")

kreiraj_index(r"docs\treca-godina\patologija\opsta-patologija", "Opsta patologija", opsta)
kreiraj_index(r"docs\treca-godina\patologija\patologija-tumora", "Patologija tumora", tumori)
kreiraj_index(r"docs\treca-godina\patologija\specijalna-patologija", "Specijalna patologija", specijalna)

print("Gotovo!")