site_name: Laganica Wiki
site_url: https://goga-ng.github.io/laganica-wiki/
repo_url: https://github.com/Goga-NG/laganica-wiki
repo_name: Goga-NG/laganica-wiki

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Tamna tema
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Svetla tema
        
nav:
  - Početna: index.md
  - Prva godina: prva-godina/index.md
  - Druga godina: druga-godina/index.md
  - Treća godina: treca-godina/index.md
  - Četvrta godina: cetvrta-godina/index.md
  - Peta godina: peta-godina/index.md
  - Šesta godina: sesta-godina/index.md